# Generated by Django 2.2.10 on 2021-10-04 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idea', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalActivity',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tool', models.CharField(blank=True, max_length=100, null=True, verbose_name='Herramienta')),
                ('annexed', models.TextField(blank=True, max_length=100, null=True, verbose_name='Anexo actividad')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripción')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre Actividad')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha de creación')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Leguas por actividad')),
                ('redeemed_score', models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Leguas canjeadas?')),
                ('link_documentation', models.URLField(blank=True, default='https://drive.google.com/', max_length=1500, null=True, verbose_name='Enlace a Documentación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Actividad',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(blank=True, max_length=100, null=True, verbose_name='Herramienta')),
                ('annexed', models.FileField(blank=True, null=True, upload_to='document_activity/', verbose_name='Anexo actividad')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripción')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre Actividad')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha de creación')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Leguas por actividad')),
                ('redeemed_score', models.BooleanField(blank=True, default=False, null=True, verbose_name='¿Leguas canjeadas?')),
                ('link_documentation', models.URLField(blank=True, default='https://drive.google.com/', max_length=1500, null=True, verbose_name='Enlace a Documentación')),
                ('id_idea', models.ManyToManyField(to='idea.Idea', verbose_name='Idea a evaluar')),
                ('id_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'permissions': (('admin_activity', 'admin_activity'),),
            },
        ),
    ]
