# Generated by Django 2.2.27 on 2023-02-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20211026_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Leguas por actividad'),
        ),
        migrations.AlterField(
            model_name='historicalactivity',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Leguas por actividad'),
        ),
    ]
