# Generated by Django 2.2.10 on 2021-10-04 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idea', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre Reunión')),
                ('date', models.DateField(null=True, verbose_name='Fecha de creación')),
                ('document_act', models.FileField(blank=True, null=True, upload_to='document_meeting/')),
                ('place', models.CharField(max_length=50, verbose_name='Lugar')),
                ('start_time', models.TimeField(null=True, verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(null=True, verbose_name='Hora Fin')),
                ('is_active', models.BooleanField(default=True, max_length=100, verbose_name='Está calificada')),
                ('link_documentation', models.URLField(blank=True, default='https://drive.google.com/', max_length=1500, null=True, verbose_name='Enlace a Documentación')),
                ('id_idea', models.ManyToManyField(to='idea.Idea')),
                ('user_comitte', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reunión Nautilus',
                'verbose_name_plural': 'Reuniones Nautilus',
            },
        ),
        migrations.CreateModel(
            name='UserVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('1', 'Por rectificar'), ('2', 'Pasa a siguiente Fase'), ('3', 'No aprobado')], max_length=100, verbose_name='Voto de la Idea')),
                ('is_evaluate', models.BooleanField(default=False, verbose_name='Está calificada')),
                ('phase_actual', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, max_length=500, null=True, verbose_name='Comentario')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date_published')),
                ('id_idea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='idea.Idea', verbose_name='Miembro Comité')),
                ('id_meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.Meeting')),
                ('id_user_comitte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto Comité Nautilus',
                'verbose_name_plural': 'Votos Comité Nautilus',
            },
        ),
        migrations.CreateModel(
            name='HistoricalUserVotes',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('vote', models.CharField(choices=[('1', 'Por rectificar'), ('2', 'Pasa a siguiente Fase'), ('3', 'No aprobado')], max_length=100, verbose_name='Voto de la Idea')),
                ('is_evaluate', models.BooleanField(default=False, verbose_name='Está calificada')),
                ('phase_actual', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, max_length=500, null=True, verbose_name='Comentario')),
                ('pub_date', models.DateTimeField(blank=True, editable=False, verbose_name='date_published')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('id_idea', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idea.Idea', verbose_name='Miembro Comité')),
                ('id_meeting', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='meeting.Meeting')),
                ('id_user_comitte', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Voto Comité Nautilus',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMeeting',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre Reunión')),
                ('date', models.DateField(null=True, verbose_name='Fecha de creación')),
                ('document_act', models.TextField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(max_length=50, verbose_name='Lugar')),
                ('start_time', models.TimeField(null=True, verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(null=True, verbose_name='Hora Fin')),
                ('is_active', models.BooleanField(default=True, max_length=100, verbose_name='Está calificada')),
                ('link_documentation', models.URLField(blank=True, default='https://drive.google.com/', max_length=1500, null=True, verbose_name='Enlace a Documentación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Reunión Nautilus',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
