# Generated by Django 2.2.27 on 2022-04-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluservotes',
            name='vote',
            field=models.CharField(choices=[('1', 'Pasa a la siguiente fase'), ('2', 'Se mantiene en la fase'), ('3', 'Sube de prioridad'), ('4', 'Baja de prioridad'), ('5', 'Descartar idea y enviar a Stand By')], max_length=100, verbose_name='Voto de la Idea'),
        ),
        migrations.AlterField(
            model_name='uservotes',
            name='vote',
            field=models.CharField(choices=[('1', 'Pasa a la siguiente fase'), ('2', 'Se mantiene en la fase'), ('3', 'Sube de prioridad'), ('4', 'Baja de prioridad'), ('5', 'Descartar idea y enviar a Stand By')], max_length=100, verbose_name='Voto de la Idea'),
        ),
    ]
