# Generated by Django 2.2.27 on 2022-04-27 10:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20220406_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluservotes',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='uservotes',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True, verbose_name='Comentario'),
        ),
    ]
