# Generated by Django 2.2.27 on 2022-04-28 16:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20220427_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluservotes',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Sin comentarios', max_length=500, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='uservotes',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Sin comentarios', max_length=500, null=True, verbose_name='Comentario'),
        ),
    ]
