# Generated by Django 2.2.27 on 2022-05-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_auto_20220428_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluservotes',
            name='message',
            field=models.CharField(blank=True, default='Sin comentarios', max_length=500, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='uservotes',
            name='message',
            field=models.CharField(blank=True, default='Sin comentarios', max_length=500, null=True, verbose_name='Comentario'),
        ),
    ]
