# Generated by Django 2.2.27 on 2023-03-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_auto_20220624_0728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalmeeting',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Reunión Comité'},
        ),
        migrations.AlterModelOptions(
            name='historicaluservotes',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Voto Comité'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': 'Reunión Comité', 'verbose_name_plural': 'Reuniones Comité'},
        ),
        migrations.AlterModelOptions(
            name='uservotes',
            options={'verbose_name': 'Voto Comité', 'verbose_name_plural': 'Votos Comité'},
        ),
        migrations.AddField(
            model_name='historicaluservotes',
            name='vote_priority',
            field=models.CharField(choices=[('1', 'Sube de prioridad'), ('2', 'Baja de prioridad'), ('3', 'Se mantiene en prioridad')], default=1, max_length=100, verbose_name='Voto de Prioridad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uservotes',
            name='vote_priority',
            field=models.CharField(choices=[('1', 'Sube de prioridad'), ('2', 'Baja de prioridad'), ('3', 'Se mantiene en prioridad')], default=1, max_length=100, verbose_name='Voto de Prioridad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaluservotes',
            name='vote',
            field=models.CharField(choices=[('1', 'Avanza de fase'), ('2', 'Se mantiene en fase'), ('3', 'Banco de Ideas')], max_length=100, verbose_name='Voto de Fase'),
        ),
        migrations.AlterField(
            model_name='uservotes',
            name='vote',
            field=models.CharField(choices=[('1', 'Avanza de fase'), ('2', 'Se mantiene en fase'), ('3', 'Banco de Ideas')], max_length=100, verbose_name='Voto de Fase'),
        ),
    ]
