# Generated by Django 2.2.27 on 2023-04-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_auto_20230421_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluservotes',
            name='vote',
            field=models.CharField(choices=[('1', 'Avanza de fase'), ('2', 'Se mantiene en fase'), ('3', 'Banco de Ideas')], max_length=100, verbose_name='Voto de Fase'),
        ),
        migrations.AlterField(
            model_name='historicaluservotes',
            name='vote_priority',
            field=models.CharField(choices=[('1', 'Sube de prioridad'), ('2', 'Baja de prioridad'), ('3', 'Se mantiene en prioridad')], max_length=100, verbose_name='Voto de Prioridad'),
        ),
        migrations.AlterField(
            model_name='uservotes',
            name='vote',
            field=models.CharField(choices=[('1', 'Avanza de fase'), ('2', 'Se mantiene en fase'), ('3', 'Banco de Ideas')], max_length=100, verbose_name='Voto de Fase'),
        ),
        migrations.AlterField(
            model_name='uservotes',
            name='vote_priority',
            field=models.CharField(choices=[('1', 'Sube de prioridad'), ('2', 'Baja de prioridad'), ('3', 'Se mantiene en prioridad')], max_length=100, verbose_name='Voto de Prioridad'),
        ),
    ]
