# Generated by Django 2.2.27 on 2023-10-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_auto_20230421_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluservotes',
            name='vote',
            field=models.CharField(choices=[('1', 'Avanza de fase'), ('2', 'Se mantiene en fase'), ('3', 'Ideas en Stand By')], max_length=100, verbose_name='Voto de Fase'),
        ),
        migrations.AlterField(
            model_name='uservotes',
            name='vote',
            field=models.CharField(choices=[('1', 'Avanza de fase'), ('2', 'Se mantiene en fase'), ('3', 'Ideas en Stand By')], max_length=100, verbose_name='Voto de Fase'),
        ),
    ]
