version: '3'

services:
 
  verne2_demo:
    image: buho/verne-copia
    command: 'python3 manage.py runserver 0.0.0.0:8006'
    volumes:
      - .:/verne-copia
    environment:
      VIRTUAL_HOST: 'verne-demo.buho.media'
      C_FORCE_ROOT: 1
      LC_ALL: 'C.UTF-8'
      LANG: 'C.UTF-8'
      TZ: 'America/Bogota'
      VIRTUAL_PORT: '8006'
      LETSENCRYPT_HOST: 'verne-demo.buho.media'
      LETSENCRYPT_EMAIL: 'sistemas@buho.media'
    networks:
        - default
        - nginx_proxy

networks:
  default:
  nginx_proxy:
    external: true


