# Generated by Django 2.2.10 on 2021-10-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalidea',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='historicalidea',
            name='link_documentation',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='link_documentation',
        ),
        migrations.AddField(
            model_name='historicalphase_date',
            name='feedback',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='historicalphase_date',
            name='link_documentation',
            field=models.URLField(blank=True, default='https://drive.google.com/', max_length=1500, null=True, verbose_name='Enlace a Documentación'),
        ),
        migrations.AddField(
            model_name='phase_date',
            name='feedback',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='phase_date',
            name='link_documentation',
            field=models.URLField(blank=True, default='https://drive.google.com/', max_length=1500, null=True, verbose_name='Enlace a Documentación'),
        ),
    ]
