# Generated by Django 2.2.10 on 2021-10-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_auto_20211004_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalphase_date',
            name='feedback',
            field=models.CharField(blank=True, default=' ', max_length=500, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='phase_date',
            name='feedback',
            field=models.CharField(blank=True, default=' ', max_length=500, null=True, verbose_name='Comentarios'),
        ),
    ]
