# Generated by Django 2.2.10 on 2021-10-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_auto_20211004_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalidea',
            name='link_documentation',
            field=models.URLField(blank=True, default='https://drive.google.com/', max_length=1500, null=True, verbose_name='Enlace a Documentación'),
        ),
        migrations.AddField(
            model_name='historicalphase_date',
            name='description',
            field=models.TextField(default='Acerca de la fase', max_length=5000, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='idea',
            name='link_documentation',
            field=models.URLField(blank=True, default='https://drive.google.com/', max_length=1500, null=True, verbose_name='Enlace a Documentación'),
        ),
        migrations.AddField(
            model_name='phase_date',
            name='description',
            field=models.TextField(default='Acerca de la fase', max_length=5000, verbose_name='Descripción'),
        ),
    ]
