# Generated by Django 2.2.10 on 2021-10-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_auto_20211011_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalphase_date',
            name='feedback',
            field=models.TextField(default='Feedback de Idea', max_length=5000, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='phase_date',
            name='feedback',
            field=models.TextField(default='Feedback de Idea', max_length=5000, verbose_name='Comentarios'),
        ),
    ]
