# Generated by Django 2.2.10 on 2021-10-14 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0007_auto_20211013_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='phase',
        ),
        migrations.AddField(
            model_name='historicalphase_date',
            name='phase',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idea.Task'),
        ),
        migrations.AddField(
            model_name='phase_date',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.Task'),
        ),
        migrations.AlterField(
            model_name='historicalidea',
            name='feedback',
            field=models.TextField(blank=True, default=' ', max_length=5000, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='feedback',
            field=models.TextField(blank=True, default=' ', max_length=5000, null=True, verbose_name='Observaciones'),
        ),
    ]
