# Generated by Django 2.2.10 on 2021-10-21 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0009_auto_20211014_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalphase_date',
            name='description',
            field=models.TextField(blank=True, default=' ', max_length=5000, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='phase_date',
            name='description',
            field=models.TextField(blank=True, default=' ', max_length=5000, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='phase_date',
            name='task',
            field=models.ManyToManyField(blank=True, to='idea.Task', verbose_name='Tareas'),
        ),
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to=None,
        ),
    ]
