# Generated by Django 2.2.10 on 2021-10-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0010_auto_20211021_1527'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to='user',
        ),
    ]
