# Generated by Django 2.2.10 on 2021-10-26 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idea', '0011_auto_20211021_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tareas por fase', 'verbose_name_plural': 'Tareas por fase'},
        ),
        migrations.AlterField(
            model_name='historicalphase_date',
            name='feedback',
            field=models.TextField(blank=True, default=' ', max_length=5000, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='phase_date',
            name='feedback',
            field=models.TextField(blank=True, default=' ', max_length=5000, null=True, verbose_name='Comentarios'),
        ),
        migrations.CreateModel(
            name='TaskByIdea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('complete', models.BooleanField(default=False, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsersIdea', to=settings.AUTH_USER_MODEL, verbose_name='Encargado')),
            ],
            options={
                'verbose_name': 'Tareas por Idea',
                'verbose_name_plural': 'Tareas por Idea',
                'order_with_respect_to': 'user',
            },
        ),
        migrations.AddField(
            model_name='idea',
            name='task',
            field=models.ManyToManyField(blank=True, to='idea.TaskByIdea', verbose_name='Tareas'),
        ),
    ]
