# Generated by Django 2.2.10 on 2021-12-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0012_auto_20211026_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='Valor Legua')),
            ],
            options={
                'verbose_name': 'Valor Legua',
                'verbose_name_plural': 'Valor Legua',
            },
        ),
        migrations.AlterField(
            model_name='historicalidea',
            name='score_idea',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Leguas invertidas'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='score_idea',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Leguas invertidas'),
        ),
    ]
