# Generated by Django 2.2.10 on 2021-12-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0013_auto_20211201_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalidea',
            name='price_score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Precio Leguas'),
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='total_investment',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Inversión'),
        ),
        migrations.AddField(
            model_name='idea',
            name='price_score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Precio Leguas'),
        ),
        migrations.AddField(
            model_name='idea',
            name='total_investment',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Inversión'),
        ),
    ]
