# Generated by Django 2.2.10 on 2022-03-08 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idea', '0015_auto_20211202_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalidea',
            name='asigned',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
        migrations.AddField(
            model_name='idea',
            name='asigned',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asigned', to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
    ]
