# Generated by Django 2.2.27 on 2022-03-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0016_auto_20220308_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalidea',
            name='owner_idea',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='owner_idea',
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
    ]
