# Generated by Django 2.2.27 on 2022-03-14 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0017_auto_20220314_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='collaborator',
            field=models.ManyToManyField(blank=True, related_name='collaborator', to=settings.AUTH_USER_MODEL, verbose_name='Autores'),
        ),
    ]
