# Generated by Django 2.2.27 on 2022-04-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0018_auto_20220314_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalidea',
            name='link_documentation',
            field=models.URLField(blank=True, default=' https://drive.google.com/', max_length=1500, null=True, verbose_name='Enlace a Documentación'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='link_documentation',
            field=models.URLField(blank=True, default=' https://drive.google.com/', max_length=1500, null=True, verbose_name='Enlace a Documentación'),
        ),
        migrations.AlterField(
            model_name='taskbyidea',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
    ]
