# Generated by Django 2.2.27 on 2022-05-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0019_auto_20220427_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'permissions': (('view_dashboard', 'view_dashboard'),), 'verbose_name': 'Idea', 'verbose_name_plural': 'Ideas'},
        ),
    ]
