# Generated by Django 2.2.27 on 2022-08-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0022_auto_20220822_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalidea',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='¿Está activa?'),
        ),
    ]
