# Generated by Django 2.2.27 on 2022-08-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0023_auto_20220824_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalidea',
            name='is_active',
        ),
        migrations.AddField(
            model_name='externalidea',
            name='state',
            field=models.CharField(blank=True, choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], max_length=20, null=True, verbose_name='Estado'),
        ),
    ]
