# Generated by Django 2.2.27 on 2022-08-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0025_auto_20220824_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalidea',
            name='feedback',
            field=models.TextField(default=1, max_length=5000, verbose_name='Comentarios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='externalidea',
            name='state',
            field=models.CharField(blank=True, choices=[('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Por definir', 'Por definir')], default='Por definir', max_length=20, null=True, verbose_name='Estado'),
        ),
    ]
