# Generated by Django 2.2.27 on 2022-09-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0026_auto_20220825_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalidea',
            name='feedback',
            field=models.TextField(default=' ', max_length=5000, verbose_name='Comentarios'),
        ),
    ]
