# Generated by Django 2.2.27 on 2023-02-15 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idea', '0027_auto_20220902_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Dimension',
                'verbose_name_plural': 'Dimensiones',
            },
        ),
        migrations.CreateModel(
            name='Frente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Frente',
                'verbose_name_plural': 'Frentes',
            },
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Gerencia',
                'verbose_name_plural': 'Gerencias',
            },
        ),
        migrations.CreateModel(
            name='Subregion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Subregion',
                'verbose_name_plural': 'Subregions',
            },
        ),
        migrations.AlterModelOptions(
            name='historicalobjective',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Objectivo'},
        ),
        migrations.AlterModelOptions(
            name='objective',
            options={'verbose_name': 'Objectivo', 'verbose_name_plural': 'Objectivos'},
        ),
        migrations.RenameField(
            model_name='historicalobjective',
            old_name='description',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='objective',
            old_name='description',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='historicalobjective',
            name='year',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='id_objective',
        ),
        migrations.RemoveField(
            model_name='objective',
            name='year',
        ),
        migrations.AddField(
            model_name='externalidea',
            name='documento',
            field=models.IntegerField(default=0, verbose_name='Cedula'),
        ),
        migrations.AddField(
            model_name='externalidea',
            name='pilar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idea.Objective', verbose_name='Pilares'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='idea_externa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idea.ExternalIdea', verbose_name='Pilares'),
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='pilar',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idea.Objective', verbose_name='Pilares'),
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='state',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='Sí', max_length=20, null=True, verbose_name='Proposito'),
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_externa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idea.ExternalIdea', verbose_name='Pilares'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='pilar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idea.Objective', verbose_name='Pilares'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='state',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='Sí', max_length=20, null=True, verbose_name='Proposito'),
        ),
        migrations.AlterField(
            model_name='externalidea',
            name='state',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='Sí', max_length=20, null=True, verbose_name='Proposito'),
        ),
        migrations.CreateModel(
            name='HistoricalSubregion',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Descripción')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Subregion',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGerencia',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Descripción')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Gerencia',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFrente',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Descripción')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Frente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDimension',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Descripción')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Dimension',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='externalidea',
            name='dimension',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idea.Dimension', verbose_name='Dimensión'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalidea',
            name='frente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idea.Frente', verbose_name='Frente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalidea',
            name='gerencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idea.Gerencia', verbose_name='Gerencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalidea',
            name='subregion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idea.Subregion', verbose_name='Subregión'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='dimension',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idea.Dimension', verbose_name='Dimensión'),
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='frente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idea.Frente', verbose_name='Frente'),
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='gerencia',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idea.Gerencia', verbose_name='Gerencia'),
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='subregion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idea.Subregion', verbose_name='Subregión'),
        ),
        migrations.AddField(
            model_name='idea',
            name='dimension',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idea.Dimension', verbose_name='Dimensión'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='frente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idea.Frente', verbose_name='Frente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='gerencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idea.Gerencia', verbose_name='Gerencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='subregion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idea.Subregion', verbose_name='Subregión'),
            preserve_default=False,
        ),
    ]
