# Generated by Django 2.2.27 on 2023-02-20 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0028_auto_20230215_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalidea',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='historicalidea',
            name='frente',
        ),
        migrations.RemoveField(
            model_name='historicalidea',
            name='gerencia',
        ),
        migrations.RemoveField(
            model_name='historicalidea',
            name='pilar',
        ),
        migrations.RemoveField(
            model_name='historicalidea',
            name='subregion',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='frente',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='gerencia',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='pilar',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='subregion',
        ),
        migrations.AlterField(
            model_name='historicalidea',
            name='idea_externa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idea.ExternalIdea', verbose_name='Idea Externa'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_externa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.ExternalIdea', verbose_name='Idea Externa'),
        ),
    ]
