# Generated by Django 2.2.27 on 2023-02-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0029_auto_20230220_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalidea',
            name='innovation_type',
            field=models.CharField(blank=True, choices=[('PROCESOS', 'Procesos'), ('Horizonte 1', 'Horizonte 1'), ('Horizonte 2', 'Horizonte 2'), ('Horizonte 3', 'Horizonte 3')], max_length=20, null=True, verbose_name='Tipo de Innovación'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='innovation_type',
            field=models.CharField(blank=True, choices=[('PROCESOS', 'Procesos'), ('Horizonte 1', 'Horizonte 1'), ('Horizonte 2', 'Horizonte 2'), ('Horizonte 3', 'Horizonte 3')], max_length=20, null=True, verbose_name='Tipo de Innovación'),
        ),
    ]
