# Generated by Django 2.2.27 on 2023-02-22 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0031_auto_20230222_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalidea',
            name='dimension',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idea.Dimension', verbose_name='Dimensión'),
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='documento',
            field=models.IntegerField(default=0, verbose_name='Cedula'),
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='frente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idea.Frente', verbose_name='Frente'),
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='gerencia',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idea.Gerencia', verbose_name='Gerencia'),
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='pilar',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idea.Objective', verbose_name='Pilares'),
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='proposito',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='Sí', max_length=20, null=True, verbose_name='Proposito'),
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='subregion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idea.Subregion', verbose_name='Subregión'),
        ),
        migrations.AddField(
            model_name='idea',
            name='dimension',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idea.Dimension', verbose_name='Dimensión'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='documento',
            field=models.IntegerField(default=0, verbose_name='Cedula'),
        ),
        migrations.AddField(
            model_name='idea',
            name='frente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idea.Frente', verbose_name='Frente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='gerencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idea.Gerencia', verbose_name='Gerencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='pilar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idea.Objective', verbose_name='Pilares'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='proposito',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='Sí', max_length=20, null=True, verbose_name='Proposito'),
        ),
        migrations.AddField(
            model_name='idea',
            name='subregion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='idea.Subregion', verbose_name='Subregión'),
            preserve_default=False,
        ),
    ]
