# Generated by Django 2.2.27 on 2023-02-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0032_auto_20230222_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalidea',
            name='external_email',
            field=models.CharField(default=1, max_length=150, verbose_name='Email externo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='external_name',
            field=models.CharField(default=1, max_length=150, verbose_name='Nombre externo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='external_email',
            field=models.CharField(default=1, max_length=150, verbose_name='Email externo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='external_name',
            field=models.CharField(default=1, max_length=150, verbose_name='Nombre externo'),
            preserve_default=False,
        ),
    ]
