# Generated by Django 2.2.27 on 2023-03-06 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0033_auto_20230222_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents_idea', verbose_name='Documentos')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
            ],
            options={
                'verbose_name': 'Documento Idea',
                'verbose_name_plural': 'Documentos Ideas',
            },
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='archivos',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idea.Archivos', verbose_name='Archivos'),
        ),
        migrations.AddField(
            model_name='idea',
            name='archivos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='idea.Archivos', verbose_name='Archivos'),
        ),
    ]
