# Generated by Django 2.2.27 on 2023-03-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0034_auto_20230306_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalidea',
            name='archivos',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='archivos',
        ),
        migrations.DeleteModel(
            name='Archivos',
        ),
    ]
