# Generated by Django 2.2.27 on 2023-03-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0035_auto_20230306_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalidea',
            name='primer_documento',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Documento Idea 1'),
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='segundo_documento',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Documento Idea 2'),
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='tercer_documento',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Documento Idea 3'),
        ),
        migrations.AddField(
            model_name='idea',
            name='primer_documento',
            field=models.FileField(blank=True, null=True, upload_to='documents_idea', verbose_name='Documento Idea 1'),
        ),
        migrations.AddField(
            model_name='idea',
            name='segundo_documento',
            field=models.FileField(blank=True, null=True, upload_to='documents_idea', verbose_name='Documento Idea 2'),
        ),
        migrations.AddField(
            model_name='idea',
            name='tercer_documento',
            field=models.FileField(blank=True, null=True, upload_to='documents_idea', verbose_name='Documento Idea 3'),
        ),
    ]
