# Generated by Django 2.2.27 on 2023-03-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0036_auto_20230306_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalidea',
            name='primer_documento',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Documentación de Evolución 1'),
        ),
        migrations.AlterField(
            model_name='historicalidea',
            name='segundo_documento',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Documentación de Evolución 2'),
        ),
        migrations.AlterField(
            model_name='historicalidea',
            name='tercer_documento',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Documentación de Evolución 3'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='primer_documento',
            field=models.FileField(blank=True, null=True, upload_to='documents_idea', verbose_name='Documentación de Evolución 1'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='segundo_documento',
            field=models.FileField(blank=True, null=True, upload_to='documents_idea', verbose_name='Documentación de Evolución 2'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='tercer_documento',
            field=models.FileField(blank=True, null=True, upload_to='documents_idea', verbose_name='Documentación de Evolución 3'),
        ),
    ]
