# Generated by Django 2.2.27 on 2023-03-13 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0037_auto_20230306_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalidea',
            name='region',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idea.Subregion', verbose_name='Regiones de aplicación de la idea'),
        ),
        migrations.AddField(
            model_name='idea',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='region_implementacion', to='idea.Subregion', verbose_name='Regiones de aplicación de la idea'),
            preserve_default=False,
        ),
    ]
