# Generated by Django 2.2.27 on 2023-03-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0040_auto_20230313_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalidea',
            name='solucion',
            field=models.TextField(default=1, max_length=5000, verbose_name='Solución'),
            preserve_default=False,
        ),
    ]
