# Generated by Django 2.2.27 on 2023-03-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0041_externalidea_solucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_implementacion', to='idea.Subregion', verbose_name='Regiones de aplicación de la idea'),
        ),
    ]
