# Generated by Django 2.2.27 on 2023-03-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0043_auto_20230315_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='region',
            field=models.ManyToManyField(blank=True, related_name='region', to='idea.Subregion', verbose_name='Regiones de aplicación de la idea'),
        ),
    ]
