# Generated by Django 2.2.27 on 2023-03-17 14:16

import apps.idea.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0044_auto_20230315_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='primer_documento',
            field=models.FileField(blank=True, null=True, upload_to=apps.idea.models.Idea.custom_upload_to_documento, verbose_name='Documentación de Evolución 1'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='segundo_documento',
            field=models.FileField(blank=True, null=True, upload_to=apps.idea.models.Idea.custom_upload_to_documento2, verbose_name='Documentación de Evolución 2'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='tercer_documento',
            field=models.FileField(blank=True, null=True, upload_to=apps.idea.models.Idea.custom_upload_to_documento3, verbose_name='Documentación de Evolución 3'),
        ),
    ]
