# Generated by Django 2.2.27 on 2023-03-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0045_auto_20230317_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='primer_documento',
            field=models.FileField(blank=True, null=True, upload_to='home', verbose_name='Documentación de Evolución 1'),
        ),
    ]
