# Generated by Django 2.2.27 on 2023-03-17 15:54

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0046_auto_20230317_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='primer_documento',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='home/'), upload_to='', verbose_name='Documentación de Evolución 1'),
        ),
    ]
