# Generated by Django 2.2.27 on 2023-03-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0050_auto_20230330_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalidea',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='Descripción de problema'),
        ),
        migrations.AlterField(
            model_name='historicalidea',
            name='solucion',
            field=models.TextField(max_length=5000, verbose_name='Solución del problema'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='Descripción de problema'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='solucion',
            field=models.TextField(max_length=5000, verbose_name='Solución del problema'),
        ),
    ]
