# Generated by Django 2.2.27 on 2023-03-30 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0051_auto_20230330_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalidea',
            name='frente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idea.Frente', verbose_name='Frente de Innovación'),
        ),
        migrations.AlterField(
            model_name='historicalidea',
            name='proposito',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='Sí', max_length=20, null=True, verbose_name='Propósito'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='frente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.Frente', verbose_name='Frente de Innovación'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='proposito',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], default='Sí', max_length=20, null=True, verbose_name='Propósito'),
        ),
    ]
