# Generated by Django 2.2.27 on 2023-04-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0052_auto_20230330_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='segundo_documento',
            field=models.FileField(blank=True, null=True, upload_to='home', verbose_name='Documentación de Evolución 2'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='tercer_documento',
            field=models.FileField(blank=True, null=True, upload_to='home', verbose_name='Documentación de Evolución 3'),
        ),
    ]
