# Generated by Django 2.2.27 on 2023-04-21 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0053_auto_20230421_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalidea',
            name='conditions',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Términos y condiciones'),
        ),
        migrations.AlterField(
            model_name='historicalidea',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Descripción de problema'),
        ),
        migrations.AlterField(
            model_name='historicalidea',
            name='documento',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='historicalidea',
            name='external_email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Email externo'),
        ),
        migrations.AlterField(
            model_name='historicalidea',
            name='external_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre externo'),
        ),
        migrations.AlterField(
            model_name='historicalidea',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='conditions',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Términos y condiciones'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Descripción de problema'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.Dimension', verbose_name='Dimensión'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='documento',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='external_email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Email externo'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='external_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre externo'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='frente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.Frente', verbose_name='Frente de Innovación'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='gerencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.Gerencia', verbose_name='Gerencia'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_externa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.ExternalIdea', verbose_name='Idea Externa'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='pilar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.Objective', verbose_name='Pilares'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='subregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.Subregion', verbose_name='Subregión'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Título'),
        ),
    ]
