# Generated by Django 2.2.27 on 2023-04-21 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0054_auto_20230421_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea_externa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.ExternalIdea', verbose_name='Idea Externa'),
        ),
    ]
