# Generated by Django 2.2.27 on 2023-04-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0055_auto_20230421_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalidea',
            name='revision',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Revision del problema'),
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='revision',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Revision del problema'),
        ),
        migrations.AddField(
            model_name='idea',
            name='revision',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Revision del problema'),
        ),
    ]
