# Generated by Django 2.2.27 on 2023-08-25 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idea', '0057_auto_20230817_1524'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gerencia',
            new_name='Area',
        ),
        migrations.RenameModel(
            old_name='Subregion',
            new_name='Beneficio',
        ),
        migrations.RenameModel(
            old_name='HistoricalGerencia',
            new_name='HistoricalArea',
        ),
        migrations.RenameModel(
            old_name='HistoricalSubregion',
            new_name='HistoricalBeneficio',
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='beneficio',
            options={'verbose_name': 'Beneficio', 'verbose_name_plural': 'Beneficios'},
        ),
        migrations.AlterModelOptions(
            name='historicalarea',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Area'},
        ),
        migrations.AlterModelOptions(
            name='historicalbeneficio',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Beneficio'},
        ),
        migrations.RemoveField(
            model_name='historicalidea',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='historicalidea',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='historicalidea',
            name='external_email',
        ),
        migrations.RemoveField(
            model_name='historicalidea',
            name='external_name',
        ),
        migrations.RemoveField(
            model_name='historicalidea',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='historicalidea',
            name='frente',
        ),
        migrations.RemoveField(
            model_name='historicalidea',
            name='gerencia',
        ),
        migrations.RemoveField(
            model_name='historicalidea',
            name='pilar',
        ),
        migrations.RemoveField(
            model_name='historicalidea',
            name='primer_documento',
        ),
        migrations.RemoveField(
            model_name='historicalidea',
            name='proposito',
        ),
        migrations.RemoveField(
            model_name='historicalidea',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='historicalidea',
            name='segundo_documento',
        ),
        migrations.RemoveField(
            model_name='historicalidea',
            name='solucion',
        ),
        migrations.RemoveField(
            model_name='historicalidea',
            name='subregion',
        ),
        migrations.RemoveField(
            model_name='historicalidea',
            name='tercer_documento',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='external_email',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='external_name',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='frente',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='gerencia',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='pilar',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='primer_documento',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='proposito',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='region',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='segundo_documento',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='solucion',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='subregion',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='tercer_documento',
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='area',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idea.Area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='beneficio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idea.Beneficio', verbose_name='Beneficio'),
        ),
        migrations.AddField(
            model_name='historicalidea',
            name='descripcion_beneficio',
            field=models.TextField(blank=True, default=' ', max_length=5000, null=True, verbose_name='Describe el beneficio'),
        ),
        migrations.AddField(
            model_name='idea',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.Area', verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='idea',
            name='beneficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.Beneficio', verbose_name='Beneficio'),
        ),
        migrations.AddField(
            model_name='idea',
            name='descripcion_beneficio',
            field=models.TextField(blank=True, default=' ', max_length=5000, null=True, verbose_name='Describe el beneficio'),
        ),
        migrations.AlterField(
            model_name='historicalidea',
            name='innovation_type',
            field=models.CharField(blank=True, choices=[('Nueva', 'Nueva'), ('En desarrollo', 'En desarrollo'), ('Implementada', 'Implementada')], max_length=20, null=True, verbose_name='¿En qué etapa se encuentra ia idea?'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='innovation_type',
            field=models.CharField(blank=True, choices=[('Nueva', 'Nueva'), ('En desarrollo', 'En desarrollo'), ('Implementada', 'Implementada')], max_length=20, null=True, verbose_name='¿En qué etapa se encuentra ia idea?'),
        ),
    ]
