# Generated by Django 2.2.27 on 2023-08-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0058_auto_20230825_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalidea',
            name='feedback',
            field=models.TextField(blank=True, default=' ', max_length=5000, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='idea',
            name='feedback',
            field=models.TextField(blank=True, default=' ', max_length=5000, null=True, verbose_name='Observaciones'),
        ),
    ]
