# Generated by Django 2.2.27 on 2023-10-25 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0060_auto_20231019_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalidea',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.Dimension', verbose_name='Dimensión'),
        ),
        migrations.AlterField(
            model_name='externalidea',
            name='documento',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='externalidea',
            name='frente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.Frente', verbose_name='Frente'),
        ),
        migrations.AlterField(
            model_name='externalidea',
            name='gerencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.Area', verbose_name='Gerencia'),
        ),
        migrations.AlterField(
            model_name='externalidea',
            name='pilar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.Objective', verbose_name='Pilares'),
        ),
        migrations.AlterField(
            model_name='externalidea',
            name='subregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.Beneficio', verbose_name='Subregión'),
        ),
    ]
