# Generated by Django 2.2.27 on 2023-11-09 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0061_auto_20231025_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalidea',
            name='id_objective',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='idea.Objective', verbose_name='Objetivos'),
        ),
        migrations.AddField(
            model_name='idea',
            name='id_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.Objective', verbose_name='Objetivos'),
        ),
        migrations.AlterField(
            model_name='externalidea',
            name='pilar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idea.Objective', verbose_name='Objetivos'),
        ),
    ]
