# Generated by Django 2.2.27 on 2023-11-09 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0062_auto_20231109_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobjective',
            name='year',
            field=models.IntegerField(default=2023, verbose_name='Año'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objective',
            name='year',
            field=models.IntegerField(default=2023, verbose_name='Año'),
            preserve_default=False,
        ),
    ]
