# Generated by Django 2.2.10 on 2021-10-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='historicalaction',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Descripción'),
        ),
    ]
