# Generated by Django 2.2.27 on 2022-04-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0002_auto_20211014_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='date_asigned',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaction',
            name='date_asigned',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historicalaction',
            name='date',
            field=models.DateField(),
        ),
    ]
