# Generated by Django 2.2.27 on 2022-06-10 13:03

import apps.prize.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0003_auto_20220406_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.prize.models.custom_upload_to, verbose_name='Imagen premio'),
        ),
        migrations.AlterField(
            model_name='userleguas',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Leguas'),
        ),
    ]
