# Generated by Django 2.2.27 on 2023-10-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prize', '0004_auto_20220610_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleguas',
            name='category',
            field=models.CharField(choices=[('1', 'Innovation Team'), ('2', 'Aprendiz'), ('3', 'Explorador'), ('4', 'Gurú')], default='1', max_length=100, verbose_name='Categoría'),
        ),
    ]
