# Generated by Django 2.2.10 on 2021-10-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title', models.CharField(default='¡Bienvenido a Verne!', max_length=100, verbose_name='Título Banner')),
                ('description', models.CharField(default='El sistema de innovación del buho lab', max_length=100, verbose_name='Descripción Banner')),
                ('image_banner', models.ImageField(default='https://chat.google.com/u/0/api/get_attachment_url?url_type=FIFE_URL&content_type=image%2Fpng&attachment_token=AAUuIGtqu2PUq2fq%2BAJi7NMgxheQKh2HrtfL2qutAvOZd5tSNJyJjLLHtXkHHtk8M3GP641u6OHHaEp4%2B71e%2B3lLVm3JzC4EsNzClK8mGkdEb%2BuUIDKHRLmaHuypx8wrJyK4UYF3Bry2xqML01Z3DymNXjuFoGP7yhcltYZ6hbhiGwDULRQ0FAQbC4K%2Fei7GPZ8OV%2FxojDqqLkTjDbYkh1OlyiMqCYuNBMXtJpVxQrnIw11vNzlG23hegYmM7Fvp5glyZMlySDotsCd7HhpWTu6KDlCHAR4M29ozITLq3z0o5JOI7ScUqR1Mn5IxQyRdmkOi457gSOzJzp11XQp9bm4kgesy%2B46r%2Ff7qeo3B9xXsK6MbB2PfIUd5QzXSQh4VxRP6vvTarI5SW3heYPeHmQ%2Bb%2Brnds2V5OWB6LgHc5RKCzhLecwxC7Q%3D%3D&sz=w512', upload_to='', verbose_name='Imagen Banner')),
            ],
            options={
                'verbose_name': 'Banner Inicio',
                'verbose_name_plural': 'Banner Inicio',
            },
        ),
        migrations.CreateModel(
            name='ExploreSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_image', models.ImageField(default='https://chat.google.com/u/0/api/get_attachment_url?url_type=FIFE_URL&content_type=image%2Fpng&attachment_token=AAUuIGsrfb%2FefbeDKV2YChWYt%2BnLao2%2FOZdqMRgRZJ0%2F72i2NJM8YfgV08tXSWisR%2B6siUsSSo6EJVWGRL3zuQi5zp5q4fZCaDPW41F%2B3%2BVGs7mPbWDQC2rGSuqdCJNyPlOrdaAkI3vofvIPXpjEbC0DHH7rx6GyXqpGBMQHjGzDI37Mq%2BsHrYkA4s39iYqkmiKC500%2B5tJ%2FRsWasmZMT3PgDCYQt%2FkrKsAWjnSrLc04GSW%2BIecZKHTgDH406eZ%2FCeNDBVsz%2FUxkUTDX0BwPeRgoMegxHooSgwit5mc5rErrcUEQhTVqGcb4n3sRv3vMbpnn19s6HyToVi5ime48g3tQ6%2Fp%2F7%2Beh9scmPB7y2cE%2FLLRZ29nNTC5lZGNyFXCj0tAGQXK11O9mvQZ5VF%2FVj9eUBYgzsaqx%2BkCyUaoyJl3Y&sz=w512', upload_to='', verbose_name='Imagen Card Sección Explora')),
                ('card_title', models.CharField(default='¿Encontraste algún pain o una oportunidad para mejorar?', max_length=100, verbose_name='Título Card Sección Explora')),
                ('card_description', models.CharField(default='Envia Ideas', max_length=100, verbose_name='Descripción Card Sección Explora')),
            ],
            options={
                'verbose_name': 'Card Sección Explora',
                'verbose_name_plural': 'Cards Sección Explora',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_footer', models.ImageField(default='https://buho.media/static/images/logo.svg', upload_to='', verbose_name='Logo Footer')),
                ('description_footer', models.CharField(default='¡Conoce más acerca de nosotros por los demás canales que tenemos!', max_length=100, verbose_name='Descripción')),
                ('link_facebook', models.URLField(default='https://www.facebook.com/buho.media/', max_length=1500, unique=True, verbose_name='Link Facebook')),
                ('link_twitter', models.URLField(default='https://twitter.com/buho_media?lang=es', max_length=1500, unique=True, verbose_name='Link Twitter')),
                ('link_linkedin', models.URLField(default='https://www.linkedin.com/company/buhomedia/mycompany/verification/', max_length=1500, unique=True, verbose_name='Link Linkedin')),
                ('address', models.CharField(default='Cra 12A # 78-40', max_length=100, verbose_name='Dirección')),
                ('location', models.CharField(default='Bogotá - México', max_length=100, verbose_name='Ubicación')),
                ('telephone', models.IntegerField(default='4954177', verbose_name='Teléfono')),
                ('url_website', models.URLField(default='www.buho.media.com', max_length=1500, unique=True, verbose_name='Link Página Web')),
                ('terms_conditions', models.URLField(blank=True, default='https://buho.media/terminos/#terminos', max_length=1500, null=True, unique=True, verbose_name='Términos y condiciones')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='HeaderExploreSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Explora la innovación', max_length=100, verbose_name='Título Sección Explora')),
                ('description', models.CharField(default='En Verne podrás participar y estar al tanto de los procesos de innovación que llevamos a cabo.', max_length=100, verbose_name='Descripción Sección Explora')),
            ],
            options={
                'verbose_name': 'Título Sección Explora',
                'verbose_name_plural': 'Título Sección Explora',
            },
        ),
        migrations.CreateModel(
            name='HeaderTeamSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Conoce al equipo', max_length=100, verbose_name='Título Sección Equipo')),
                ('description', models.CharField(default='Este es el equipo detrás del buho lab, el área de innovación de buho media', max_length=100, verbose_name='Descripción Sección Equipo')),
            ],
            options={
                'verbose_name': 'Título Sección Equipo',
                'verbose_name_plural': 'Título Sección Equipo',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(default='Inicio', max_length=20, verbose_name='Itmes Menú')),
            ],
            options={
                'verbose_name': 'Item Menú',
                'verbose_name_plural': 'Items Menú',
            },
        ),
        migrations.CreateModel(
            name='MenuLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='https://buho.media/static/images/logo.svg', upload_to='', verbose_name='Imagen Logo')),
            ],
            options={
                'verbose_name': 'Logo Principal',
                'verbose_name_plural': 'Logo Principal',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conter_data', models.IntegerField(default='250', verbose_name='Contador Métricas')),
                ('title_counter', models.CharField(default='Ideas Recibidas', max_length=100, verbose_name='Título Métricas')),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
            },
        ),
        migrations.CreateModel(
            name='ProcessSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_image', models.ImageField(default='https://chat.google.com/u/0/api/get_attachment_url?url_type=FIFE_URL&content_type=image%2Fpng&attachment_token=AAUuIGv6HNqnXsYBtEMGvXeyeDCSLiDvqZbPOez9C%2BStdOkEeFlnhsM8iDP%2F1MKQ5pnJBUdY8a42SthmSTop8wwxB9wNVjwT7tep3%2FTaV8x8vwI3tJHYs1e08mjLyBFACjQuP3Q3X4ADU0THNIzTszdaBoKQ2YQvOzhUYGwncjEfGTDSA%2F9G06ADNgupghwOEpYJGn9w5%2B%2FK0yOe0a%2BzpYD%2BcCBmvwHR5qde7bXmKm2vxg0XbekgLFzVuGN%2BkjHFI1L6uxRDIPAJat6um5651T6bLVB8eCPm%2FlrDjSmqd5rhN4MeZ%2FzXpleL9tP2IF3a4thD%2BY9vZ%2BvKm9qrOmk3l01F1J3Oe%2FljLkHnUDE72WKL%2FffU%2BGsbvjNli%2F4oUQNzPuxSO8ETFwI0qUHOk7UejSnRT9RHxki9N7m7X86kM8Ml7EN2GAVLfQ%3D%3D&sz=w512', upload_to='', verbose_name='Imagen Sección Procesos')),
                ('card_title', models.CharField(default='Empezamos en observación', max_length=100, verbose_name='Título Sección Procesos')),
                ('card_description', models.TextField(default='Esta es la primera fase del proceso de innovación ', max_length=1000, verbose_name='Descripción Sección Procesos')),
                ('card_description_two', models.TextField(blank=True, default='También en esta fase identificamos patrones de comportamiento', max_length=1000, null=True, verbose_name='Descripción Sección Procesos')),
            ],
            options={
                'verbose_name': 'Card Sección Procesos',
                'verbose_name_plural': 'Cards Sección Procesos',
            },
        ),
        migrations.CreateModel(
            name='TeamSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_image', models.ImageField(default='https://chat.google.com/u/0/api/get_attachment_url?url_type=FIFE_URL&content_type=image%2Fpng&attachment_token=AAUuIGtuK0XRXYfLw77ylGc5zL651zQbg8yBxfS0joXlnooeRgY4TKNPoKwM7MXxtomeE7IO%2FXiA6U9t9KVHLEEFyQv2bOnZYbcW7NsXPo1VYnoq8DKTjcMtmuW4os9iTu%2FbDKOHkBdxYrRlWtC%2BfRoMKi74RIFfPA9lDmh%2BaOcTz%2FpOUSy2L5vw6XWvYZEzOilo1tdWQdCyhb4bQrdCK%2FF3z2MxDgaU1ZYRSdy85YrGm5Vk6LrcMZLm7DAn6v8iVTMejf6SkDEWG9j2c0Ygp8gd%2B1Pad%2BrfSNotrbqHD7rAiBvsiUy6RJWYm%2FHRplDj1asnnD7OaDzSND9Uojab6hYlIn%2Fjcu%2BE7KE%2BVwdZmROp%2FaLhDz26bFmkfBnupjsCQsxNCuhfQf9PpG9m6dWdiPfeDryAjLwl52iYkeGAOIUfgehLBRGR&sz=w512', upload_to='', verbose_name='Imagen Miembro Equipo Innovación')),
                ('team_name', models.CharField(default='Paula Díaz', max_length=100, verbose_name='Nombre Miembro Equipo Innovación')),
                ('team_role', models.CharField(default='Gerente de Innovación', max_length=100, verbose_name='Cargo Miembro Equipo Innovación')),
            ],
            options={
                'verbose_name': 'Miembro Equipo',
                'verbose_name_plural': 'Miembros Equipo',
            },
        ),
    ]
