# Generated by Django 2.2.10 on 2021-10-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211004_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='Opción Menú')),
            ],
            options={
                'verbose_name': 'Menú Lateral',
                'verbose_name_plural': 'Menú Lateral',
            },
        ),
    ]
