# Generated by Django 2.2.10 on 2021-10-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_platformmenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatformMenu',
        ),
    ]
