# Generated by Django 2.2.10 on 2021-10-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_platformmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='link_youtube',
            field=models.URLField(blank=True, max_length=1500, null=True, unique=True, verbose_name='Link Youtube'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='link_facebook',
            field=models.URLField(blank=True, max_length=1500, null=True, unique=True, verbose_name='Link Facebook'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='link_linkedin',
            field=models.URLField(blank=True, max_length=1500, null=True, unique=True, verbose_name='Link Linkedin'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='link_twitter',
            field=models.URLField(blank=True, max_length=1500, null=True, unique=True, verbose_name='Link Twitter'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='telephone',
            field=models.CharField(max_length=100, verbose_name='Teléfono'),
        ),
    ]
