# Generated by Django 2.2.10 on 2021-10-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211008_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='terms_conditions',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='', verbose_name='Términos y condiciones'),
        ),
    ]
