# Generated by Django 2.2.27 on 2022-06-10 13:03

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211027_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerheader',
            name='image_banner',
            field=models.ImageField(upload_to=apps.home.models.custom_upload_to_banner, verbose_name='Imagen Banner'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=models.CharField(max_length=20, verbose_name='Items Menú'),
        ),
        migrations.AlterField(
            model_name='menulogo',
            name='logo',
            field=models.ImageField(upload_to=apps.home.models.custom_upload_to_logo, verbose_name='Imagen Logo'),
        ),
    ]
