# Generated by Django 2.2.27 on 2023-03-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220610_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='manifiesto',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='', verbose_name='Manifiesto de Innovación'),
        ),
    ]
