# Generated by Django 2.2.27 on 2023-03-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_footer_manifiesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovilizadoresSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_image', models.ImageField(upload_to='', verbose_name='Imagen Miembro Movilizador Innovación')),
                ('team_name', models.CharField(max_length=100, verbose_name='Nombre Miembro Movilizador Innovación')),
                ('team_role', models.CharField(max_length=100, verbose_name='Cargo Miembro Movilizador Innovación')),
            ],
            options={
                'verbose_name': 'Movilizador de Innovación',
                'verbose_name_plural': 'Movilizadores de Innovación',
            },
        ),
    ]
