# Generated by Django 2.2.27 on 2023-03-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_movilizadoressection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderMovilizadoresSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título Sección Movilizadores')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción Sección Movilizadores')),
            ],
            options={
                'verbose_name': 'Título Sección Movilizadores',
                'verbose_name_plural': 'Título Sección Movilizadores',
            },
        ),
    ]
