# Generated by Django 2.2.27 on 2023-04-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_headermovilizadoressection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoressSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_image', models.ImageField(upload_to='', verbose_name='Imagen Nuestros Valores de Innovación')),
                ('team_name', models.CharField(max_length=100, verbose_name='Nombre Nuestros Valores de Innovación')),
                ('team_role', models.CharField(max_length=100, verbose_name='Cargo Nuestros Valores de Innovación')),
            ],
            options={
                'verbose_name': 'Nuestros Valores de Innovación',
                'verbose_name_plural': 'Nuestros Valores de Innovación',
            },
        ),
    ]
