# Generated by Django 2.2.27 on 2023-04-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_valoresssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderValoresSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título Nuestros Valores de Innovación')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción Nuestros Valores de Innovación')),
            ],
            options={
                'verbose_name': 'Título Nuestros Valores de Innovación',
                'verbose_name_plural': 'Título Sección Movilizadores',
            },
        ),
    ]
