# Generated by Django 2.2.27 on 2023-04-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_headervaloressection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headervaloressection',
            options={'verbose_name': 'Título Nuestros Valores de Innovación', 'verbose_name_plural': 'Título Nuestros Valores de Innovación'},
        ),
    ]
