# Generated by Django 2.2.27 on 2024-01-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20230410_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['id'], 'verbose_name': 'Item Menú', 'verbose_name_plural': 'Items Menú'},
        ),
    ]
