# Generated by Django 2.2.10 on 2021-10-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_template_power_bi', models.URLField(default='https://app.powerbi.com/view?r=eyJrIjoiZDQwZmMwYTYtMWIwMC00MGQ0LWJiNzgtOWE5NWE5YTgxNjlmIiwidCI6IjVlNmY0NzE0LTk4YmQtNGRhMS1hOGY1LTNjYTQ1OWVhYmRjOSIsImMiOjR9', max_length=1500, unique=True, verbose_name='Link Plantilla Power BI')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
    ]
