# Generated by Django 2.2.10 on 2021-12-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_participation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
