# Generated by Django 2.2.27 on 2022-03-16 21:39

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220316_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default-user.png', null=True, upload_to=apps.users.models.custom_upload_to),
        ),
    ]
