# Generated by Django 2.2.27 on 2022-03-18 14:10

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220316_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default-user.png', upload_to=apps.users.models.custom_upload_to),
        ),
    ]
