# Generated by Django 2.2.27 on 2022-06-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220318_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rol_company',
            field=models.TextField(blank=True, default='Por definir', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='biografy',
            field=models.TextField(blank=True, default='Nada sobre ti', null=True),
        ),
    ]
