# Generated by Django 2.2.27 on 2022-06-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220610_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_img', models.ImageField(default='default-user.png', upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='biografy',
            field=models.TextField(blank=True, default='Por definir', max_length=700, null=True),
        ),
    ]
