# Generated by Django 2.2.27 on 2022-06-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220610_1555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avatars',
            new_name='Avatar',
        ),
    ]
