# Generated by Django 2.2.27 on 2022-06-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220610_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar_img',
            field=models.ImageField(default='default-user.png', upload_to='profiles/'),
        ),
    ]
