# Generated by Django 2.2.27 on 2022-06-24 07:28

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220613_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default-user.png', upload_to=apps.users.models.custom_upload_to, verbose_name='Imagen de perfil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='biografy',
            field=models.TextField(blank=True, default='Por definir', max_length=700, null=True, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rol_company',
            field=models.TextField(blank=True, default='Por definir', null=True, verbose_name='Cargo'),
        ),
    ]
